site_name: BLE_Intro

pages:
- ['index.md','Introduction to mbed BLE']
- ['GettingStarted/UsingBLE.md', 'Getting Started', 'Intro to BLE']
- ['GettingStarted/Prototypes.md', 'Getting Started','Prototyping a BLE Project']
- ['InDepth/BLEInDepth.md','BLE in Depth', 'Modes and Profiles']
- ['InDepth/ConnectionParameters.md','BLE in Depth', 'Connection Parameters']
- ['InDepth/Limitations.md','BLE in Depth', 'BLE Limitations']
- ['InDepth/Pucks.md','BLE in Depth', 'Pucks']
- ['InDepth/CreatingServices.md','BLE in Depth', 'Creating Services']
